[tool.poetry]
name = "aegis-pentest-automation"
version = "1.0.0"
description = "Automatización de pentesting web con GUI Qt - Wrapper de herramientas de seguridad"
authors = ["Aegis Security <aegis@security.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "aegis_pentest"}]

[tool.poetry.dependencies]
python = "^3.10"
PyQt6 = "^6.6.0"
requests = "^2.31.0"
python-nmap = "^0.7.1"
pexpect = "^4.9.0"
beautifulsoup4 = "^4.12.2"
colorama = "^0.4.6"
click = "^8.1.7"
python-docx = "^1.1.0"
jinja2 = "^3.1.2"
pyyaml = "^6.0.1"
aiohttp = "^3.9.1"
dataclasses = {version = "^0.8", python = "<3.7"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
black = "^23.11.0"
flake8 = "^6.1.0"
mypy = "^1.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
aegis-pentest = "aegis_pentest.main:main_sync" 